### ISSUE TITLE
The port 3000 (http://localhost:3000) is not open after deploying with docker compose

### ISSUE THREAD

**Issue by PieBru** [TransformerOptimus/SuperAGI#1408]
### ⚠️ Check for existing issues before proceeding. ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Where are you using SuperAGI?

Linux

### Which branch of SuperAGI are you using?

Main

### Do you use OpenAI GPT-3.5 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

This is my patched  `docker-compose-gpu.yaml`:
```yaml
version: '3.8'
services:
  backend:
    volumes:
      - "./:/app"
      - "/home/piero/Piero/AI_Lab/LLM/GGUF/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf:/app/local_model_path"
    build:
      context: .
      dockerfile: Dockerfile-gpu 
    depends_on:
      - super__redis
      - super__postgres
    networks:
      - super_network
    command: ["/app/wait-for-it.sh", "super__postgres:5432","-t","60","--","/app/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  celery:
    volumes:
      - "./:/app"
      - "${EXTERNAL_RESOURCE_DIR:-./workspace}:/app/ext"
      - "/home/piero/Piero/AI_Lab/LLM/GGUF/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf:/app/local_model_path"
    build:
      context: .
      dockerfile: Dockerfile-gpu 
    depends_on:
      - super__redis
      - super__postgres
    networks:
      - super_network
    command: ["/app/entrypoint_celery.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  gui:
    build:
      context: ./gui
      args:
        NEXT_PUBLIC_API_BASE_URL: "/api"
    networks:
      - super_network
#    volumes:
#      - ./gui:/app
#      - /app/node_modules/
#      - /app/.next/
  super__redis:
    image: "redis/redis-stack-server:latest"
    networks:
      - super_network
#    uncomment to expose redis port to host
#    ports:
#      - "6379:6379"
    volumes:
      - redis_data:/data

  super__postgres:
    image: "docker.io/library/postgres:15"
    environment:
      - POSTGRES_USER=superagi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=super_agi_main
    volumes:
      - superagi_postgres_data:/var/lib/postgresql/data/
    networks:
      - super_network
#    uncomment to expose postgres port to host
#    ports:
#      - "5432:5432"

  proxy:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    networks:
      - super_network
    depends_on:
      - backend
      - gui
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  super_network:
    driver: bridge
volumes:
  superagi_postgres_data:
  redis_data:
```

I'm on Arch Linux, using podman and the podman docker compose compatibility package.

`nmap` shows port 3000 as closed.

### How to replicate your Issue?

```bash
$ conda create -n SuperAGI python=3.11
$ conda activate SuperAGI
$ git clone https://github.com/TransformerOptimus/SuperAGI.git 
$ cd SuperAGI/
$ cp config_template.yaml config.yaml
$ nano config.yaml

$ docker compose -f docker-compose-gpu.yml up --build
```

`config.yaml`:
```yaml
# config.yaml
OPENAI_API_BASE: https://192.168.111.181:11434/v1
MODEL_NAME: "mistral"
RESOURCES_SUMMARY_MODEL_NAME: "mistral"
MAX_MODEL_TOKEN_LIMIT: 2048
FRONTEND_URL: "http://localhost:3001"
```

The `OPENAI_API_BASE` works as expected. The port 3000 is free, no other processes use it.

### Upload Error Log Content

Complete log: ```log $  docker compose -f docker-compose-gpu.yml up --build Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg. >>>> Executing external compose provider "/usr/bin/podman-compose". Please refer to the documentation for details. <<<<  podman-compose version: 1.0.6 ['podman', '--version', ''] using podman version: 4.9.3 ** excluding:  set() podman build -f ./gui/Dockerfile -t superagi_gui --build-arg NEXT_PUBLIC_API_BASE_URL=/api ./gui WARN[0000] missing "NEXT_PUBLIC_MIXPANEL_AUTH_ID" build argument. Try adding "--build-arg NEXT_PUBLIC_MIXPANEL_AUTH_ID=<VALUE>" to the command line  [1/2] STEP 1/5: FROM node:18-alpine AS deps [1/2] STEP 2/5: RUN apk add --no-cache libc6-compat --> Using cache 5b781202254b1a2164155fbfc7db41c5ddf0e63cd87206db41d3a7f8e85e3609 --> 5b781202254b [1/2] STEP 3/5: WORKDIR /app --> Using cache 37c48194d600afe3583faf6ed5dcd28d2ddae926e40b4d60cd36685c911882a0 --> 37c48194d600 [1/2] STEP 4/5: COPY package.json package-lock.json ./ --> Using cache f47f3d9feaaef27a8c698c0a2dfab3b911c771deb38522c170fed541573f3d42 --> f47f3d9feaae [1/2] STEP 5/5: RUN npm ci --> Using cache 0d8d7fa72394a8b763b0daa27697f5c5ab6929c6c759678d3e45e661e22a09d6 --> 0d8d7fa72394 [2/2] STEP 1/10: FROM node:18-alpine AS builder [2/2] STEP 2/10: WORKDIR /app --> Using cache 5a76812b66d34f481b9788fdd25de5ba2c14a883c221f3ca3a03e14c172d27e8 --> 5a76812b66d3 [2/2] STEP 3/10: COPY --from=deps /app/node_modules ./node_modules --> Using cache d02a5483ac5b250df9c0c96209ad435aab59ff041a0437cd16a85260f22d0031 --> d02a5483ac5b [2/2] STEP 4/10: COPY . . --> Using cache 1e27ac87716072c26ad93ec4ffe2c8a2af910c5c0407160f5ffa74e45db6489e --> 1e27ac877160 [2/2] STEP 5/10: ARG NEXT_PUBLIC_API_BASE_URL=/api --> Using cache 6ee372748af76decbbe6e5ebb482e255758174dcdf2a84c068e473723a2fb0bf --> 6ee372748af7 [2/2] STEP 6/10: ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL --> Using cache 11cc373d0fdbeacce813431b561cc25d79d95ee0e6a19f804f5d45cdd448f423 --> 11cc373d0fdb [2/2] STEP 7/10: ARG NEXT_PUBLIC_MIXPANEL_AUTH_ID --> Using cache 3709e33acac6e4d735856f8a0dd764c5bea199dab4af621174de56ce8cbbd9ad --> 3709e33acac6 [2/2] STEP 8/10: ENV NEXT_PUBLIC_MIXPANEL_AUTH_ID=$NEXT_PUBLIC_MIXPANEL_AUTH_ID --> Using cache 572e6dbaa020c4af332719f421f2bf9cbd528f0bbce6808914f1872432bb9d00 --> 572e6dbaa020 [2/2] STEP 9/10: EXPOSE 3000 --> Using cache 32dd50355515b5db05fc93586dbc80098f5db8513fdce1ca0af6fcf1c27d9294 --> 32dd50355515 [2/2] STEP 10/10: CMD ["npm", "run", "dev"] --> Using cache 2b32bbb4a574e88e61f505279759629b58815a438ab8368f4d6cfd436fa551eb [2/2] COMMIT superagi_gui --> 2b32bbb4a574 Successfully tagged localhost/superagi_gui:latest 2b32bbb4a574e88e61f505279759629b58815a438ab8368f4d6cfd436fa551eb exit code: 0 podman build -f ./Dockerfile-gpu -t superagi_backend . STEP 1/16: FROM nvidia/cuda:12.1.1-devel-ubuntu22.04 Error: creating build container: short-name "nvidia/cuda:12.1.1-devel-ubuntu22.04" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf" exit code: 125 podman build -f ./Dockerfile-gpu -t superagi_celery . STEP 1/16: FROM nvidia/cuda:12.1.1-devel-ubuntu22.04 Error: creating build container: short-name "nvidia/cuda:12.1.1-devel-ubuntu22.04" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf" exit code: 125 ['podman', 'ps', '--filter', 'label=io.podman.compose.project=superagi', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}'] ['podman', 'network', 'exists', 'superagi_super_network'] podman create --name=superagi_gui_1 --label io.podman.compose.config-hash=12fec1722081755cf2a38e70c7a800c72251e8dab390f778df2b8c00eadab55e --label io.podman.compose.project=superagi --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@superagi.service --label com.docker.compose.project=superagi --label com.docker.compose.project.working_dir=/home/piero/Piero/AI_Lab/Github/SuperAGI --label com.docker.compose.project.config_files=docker-compose-gpu.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=gui --net superagi_super_network --network-alias gui superagi_gui b1958e18e305c13ff09c7449ba41bdb554123c1ef374b5fe6af4f4cf174b7a9e exit code: 0 podman volume inspect superagi_redis_data || podman volume create superagi_redis_data ['podman', 'volume', 'inspect', 'superagi_redis_data'] ['podman', 'network', 'exists', 'superagi_super_network'] podman create --name=superagi_super__redis_1 --label io.podman.compose.config-hash=12fec1722081755cf2a38e70c7a800c72251e8dab390f778df2b8c00eadab55e --label io.podman.compose.project=superagi --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@superagi.service --label com.docker.compose.project=superagi --label com.docker.compose.project.working_dir=/home/piero/Piero/AI_Lab/Github/SuperAGI --label com.docker.compose.project.config_files=docker-compose-gpu.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=super__redis -v superagi_redis_data:/data --net superagi_super_network --network-alias super__redis redis/redis-stack-server:latest Error: short-name "redis/redis-stack-server:latest" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf" exit code: 125 podman volume inspect superagi_superagi_postgres_data || podman volume create superagi_superagi_postgres_data ['podman', 'volume', 'inspect', 'superagi_superagi_postgres_data'] ['podman', 'network', 'exists', 'superagi_super_network'] podman create --name=superagi_super__postgres_1 --label io.podman.compose.config-hash=12fec1722081755cf2a38e70c7a800c72251e8dab390f778df2b8c00eadab55e --label io.podman.compose.project=superagi --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@superagi.service --label com.docker.compose.project=superagi --label com.docker.compose.project.working_dir=/home/piero/Piero/AI_Lab/Github/SuperAGI --label com.docker.compose.project.config_files=docker-compose-gpu.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=super__postgres -e POSTGRES_USER=superagi -e POSTGRES_PASSWORD=password -e POSTGRES_DB=super_agi_main -v superagi_superagi_postgres_data:/var/lib/postgresql/data/ --net superagi_super_network --network-alias super__postgres docker.io/library/postgres:15 bdd20427cf9b695a387335a09aa4aaec5d3a24d46f5e3c0ea6c7404c597d03cf exit code: 0 ['podman', 'network', 'exists', 'superagi_super_network'] podman create --name=superagi_backend_1 --requires=superagi_super__redis_1,superagi_super__postgres_1 --label io.podman.compose.config-hash=12fec1722081755cf2a38e70c7a800c72251e8dab390f778df2b8c00eadab55e --label io.podman.compose.project=superagi --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@superagi.service --label com.docker.compose.project=superagi --label com.docker.compose.project.working_dir=/home/piero/Piero/AI_Lab/Github/SuperAGI --label com.docker.compose.project.config_files=docker-compose-gpu.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=backend -v /home/piero/Piero/AI_Lab/Github/SuperAGI:/app -v /home/piero/Piero/AI_Lab/LLM/GGUF/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf:/app/local_model_path --net superagi_super_network --network-alias backend superagi_backend /app/wait-for-it.sh super__postgres:5432 -t 60 -- /app/entrypoint.sh Error: short-name "superagi_backend" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf" exit code: 125 ['podman', 'network', 'exists', 'superagi_super_network'] podman create --name=superagi_celery_1 --requires=superagi_super__redis_1,superagi_super__postgres_1 --label io.podman.compose.config-hash=12fec1722081755cf2a38e70c7a800c72251e8dab390f778df2b8c00eadab55e --label io.podman.compose.project=superagi --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@superagi.service --label com.docker.compose.project=superagi --label com.docker.compose.project.working_dir=/home/piero/Piero/AI_Lab/Github/SuperAGI --label com.docker.compose.project.config_files=docker-compose-gpu.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=celery -v /home/piero/Piero/AI_Lab/Github/SuperAGI:/app -v /home/piero/Piero/AI_Lab/Github/SuperAGI/workspace:/app/ext -v /home/piero/Piero/AI_Lab/LLM/GGUF/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q6_K.gguf:/app/local_model_path --net superagi_super_network --network-alias celery superagi_celery /app/entrypoint_celery.sh Error: short-name "superagi_celery" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf" exit code: 125 ['podman', 'network', 'exists', 'superagi_super_network'] podman create --name=superagi_proxy_1 --requires=superagi_super__redis_1,superagi_gui_1,superagi_super__postgres_1,superagi_backend_1 --label io.podman.compose.config-hash=12fec1722081755cf2a38e70c7a800c72251e8dab390f778df2b8c00eadab55e --label io.podman.compose.project=superagi --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@superagi.service --label com.docker.compose.project=superagi --label com.docker.compose.project.working_dir=/home/piero/Piero/AI_Lab/Github/SuperAGI --label com.docker.compose.project.config_files=docker-compose-gpu.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=proxy -v /home/piero/Piero/AI_Lab/Github/SuperAGI/nginx/default.conf:/etc/nginx/conf.d/default.conf --net superagi_super_network --network-alias proxy -p 3000:80 nginx:stable-alpine Error: short-name "nginx:stable-alpine" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf" exit code: 125 podman start -a superagi_gui_1 WARN[0000] aardvark-dns binary not found, container dns will not be enabled  [gui]             |  [gui]             | > super-agi@0.1.0 dev [gui]             | > next dev [gui]             |  podman start -a superagi_super__redis_1 [gui]             | - ready started server on 0.0.0.0:3000, url: http://localhost:3000 Error: no container with name or ID "superagi_super__redis_1" found: no such container exit code: 125 [gui]             | Attention: Next.js now collects completely anonymous telemetry regarding usage. [gui]             | This information is used to shape Next.js' roadmap and prioritize features. [gui]             | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL: [gui]             | https://nextjs.org/telemetry [gui]             |  podman start -a superagi_super__postgres_1 WARN[0000] aardvark-dns binary not found, container dns will not be enabled  [super__postgres] |  [super__postgres] | PostgreSQL Database directory appears to contain a database; Skipping initialization [super__postgres] |  2024-02-27 10:35:08.779 UTC [1] LOG:  starting PostgreSQL 15.6 (Debian 15.6-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit 2024-02-27 10:35:08.779 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432 2024-02-27 10:35:08.779 UTC [1] LOG:  listening on IPv6 address "::", port 5432 2024-02-27 10:35:08.785 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432" 2024-02-27 10:35:08.794 UTC [24] LOG:  database system was shut down at 2024-02-27 10:32:40 UTC 2024-02-27 10:35:08.800 UTC [1] LOG:  database system is ready to accept connections podman start -a superagi_backend_1 Error: no container with name or ID "superagi_backend_1" found: no such container exit code: 125 podman start -a superagi_celery_1 Error: no container with name or ID "superagi_celery_1" found: no such container exit code: 125 podman start -a superagi_proxy_1 Error: no container with name or ID "superagi_proxy_1" found: no such container exit code: 125 Browserslist: caniuse-lite is outdated. Please run:   npx browserslist@latest --update-db   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating [gui]             | - event compiled client and server successfully in 7.5s (1718 modules) [gui]             | - wait compiling... [gui]             | - event compiled client and server successfully in 452 ms (1718 modules) 2024-02-27 10:40:08.894 UTC [22] LOG:  checkpoint starting: time 2024-02-27 10:40:08.931 UTC [22] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.010 s, sync=0.006 s, total=0.037 s; sync files=2, longest=0.003 s, average=0.003 s; distance=0 kB, estimate=0 kB ```
