### ISSUE TITLE
Change gui port ?

### ISSUE THREAD

**Issue by Hedronmx** [TransformerOptimus/SuperAGI#361]
I tried changing the GUI port on docket compose file but it did not work. Am I doing something wrong? Thanks you

**Comment by neelayan7** [comment]
Can you send the docker compose file?

**Comment by lukemilby** [comment]
You'll need to update to docker-compose gui section to look something 
```
   gui:
     build: ./gui
     ports:
        - "4444:3000"
```

4444 is the port you want to access from the browser
